In [113]:
# Import de librairie
import pandas as pd
import numpy as np

# Database dechets par habitants

In [114]:
annees = [str(annee) for annee in range(2003, 2022)]

In [115]:
Data_dechets= []
for annee in annees:
    data_d = pd.read_excel(
        "Dechet_par_habitant.xls",
        sheet_name=annee,        
        skiprows=1,              
        usecols="A:B",          
        header=None,             
        names=["Commune", "Dechet_par_habitant_kg"]
    )
    data_d["Année"] = int(annee)     
    Data_dechets.append(data_d) 

Data_dechets_final = pd.concat(Data_dechets, ignore_index=True)

print(Data_dechets_final)
print(type(Data_dechets_final))

           Commune  Dechet_par_habitant_kg  Année
0    Aire-la-Ville              440.700000   2003
1          Anières              622.300000   2003
2           Avully              482.100000   2003
3            Avusy              447.900000   2003
4        Bardonnex              441.100000   2003
..             ...                     ...    ...
850        Troinex              464.605701   2021
851    Vandoeuvres              613.053812   2021
852        Vernier              408.657247   2021
853        Versoix              371.930217   2021
854        Veyrier              535.479049   2021

[855 rows x 3 columns]
<class 'pandas.core.frame.DataFrame'>

In [116]:
Data_dechets_final = Data_dechets_final [["Commune", "Année", "Dechet_par_habitant_kg"]]
Data_dechets_final = Data_dechets_final.sort_values(by=["Commune", "Année"])

Data_dechets_final = Data_dechets_final.reset_index(drop=True)

print(Data_dechets_final)

           Commune  Année  Dechet_par_habitant_kg
0    Aire-la-Ville   2003              440.700000
1    Aire-la-Ville   2004              442.000000
2    Aire-la-Ville   2005              389.200000
3    Aire-la-Ville   2006              388.700000
4    Aire-la-Ville   2007              377.500000
..             ...    ...                     ...
850        Veyrier   2017              458.800000
851        Veyrier   2018              403.400000
852        Veyrier   2019              377.400000
853        Veyrier   2020              426.000000
854        Veyrier   2021              535.479049

[855 rows x 3 columns]

In [117]:

dechet_moyennes_par_annee = Data_dechets_final.groupby('Année')['Dechet_par_habitant_kg'].mean().reset_index()
#print(dechet_moyennes_par_annee )

# Créer le dataframe des moyennes
dechet_moyennes =dechet_moyennes_par_annee.copy()
dechet_moyennes['Commune'] = 'Moyenne_' + dechet_moyennes['Année'].astype(str)

Data_dechets_final = pd.concat([Data_dechets_final, dechet_moyennes], ignore_index=True)
print(Data_dechets_final)
Data_dechets_final = Data_dechets_final.sort_values(['Année', 'Commune'])
print(Data_dechets_final)
Data_dechets_final.to_csv("donnees_dechet_par_habitant.csv")

           Commune  Année  Dechet_par_habitant_kg
0    Aire-la-Ville   2003              440.700000
1    Aire-la-Ville   2004              442.000000
2    Aire-la-Ville   2005              389.200000
3    Aire-la-Ville   2006              388.700000
4    Aire-la-Ville   2007              377.500000
..             ...    ...                     ...
869   Moyenne_2017   2017              441.768889
870   Moyenne_2018   2018              432.253333
871   Moyenne_2019   2019              435.862222
872   Moyenne_2020   2020              443.968889
873   Moyenne_2021   2021              457.900241

[874 rows x 3 columns]
           Commune  Année  Dechet_par_habitant_kg
0    Aire-la-Ville   2003              440.700000
19         Anières   2003              622.300000
38          Avully   2003              482.100000
57           Avusy   2003              447.900000
76       Bardonnex   2003              441.100000
..             ...    ...                     ...
778        Troinex   2021              464.605701
797    Vandoeuvres   2021              613.053812
816        Vernier   2021              408.657247
835        Versoix   2021              371.930217
854        Veyrier   2021              535.479049

[874 rows x 3 columns]

# Database densité de la population

In [118]:
Data_densite = pd.read_excel("densité_de_la_population.xls")

Data_densite_reviewed = Data_densite.melt(id_vars=[Data_densite.columns[0]],var_name="Année", value_name="Densité_km2")
Data_densite_reviewed
Data_densite_reviewed.rename(columns={Data_densite.columns[0]: "Commune"}, inplace=True)

Data_densite_reviewed = Data_densite_reviewed.sort_values(by=["Commune", "Année"])

Data_densite_reviewed = Data_densite_reviewed .reset_index(drop=True)
Data_densite_reviewed

           Commune Année  Densité_km2
0    Aire-la-Ville  2005   286.000000
1    Aire-la-Ville  2006   311.000000
2    Aire-la-Ville  2007   374.000000
3    Aire-la-Ville  2008   383.000000
4    Aire-la-Ville  2009   389.000000
..             ...   ...          ...
895        Veyrier  2020  1829.000000
896        Veyrier  2021  1823.000000
897        Veyrier  2022  1836.000000
898        Veyrier  2023  1835.368468
899        Veyrier  2024  1858.764645

[900 rows x 3 columns]

In [119]:
densite_moyennes_par_annee = Data_densite_reviewed.groupby('Année')['Densité_km2'].mean().reset_index()

# Créer le dataframe des moyennes
densite_moyennes =densite_moyennes_par_annee.copy()
densite_moyennes['Commune'] = 'Moyenne_' + dechet_moyennes['Année'].astype(str)

Data_densite_final = pd.concat([Data_densite_reviewed, densite_moyennes], ignore_index=True)
Data_densite_final = Data_densite_final.sort_values(['Année', 'Commune'])
print(Data_densite_final)
Data_densite_final.to_csv("donnée_densité_population.csv")

           Commune Année  Densité_km2
0    Aire-la-Ville  2005   286.000000
20         Anières  2005   613.000000
40          Avully  2005   388.000000
60           Avusy  2005   242.000000
80       Bardonnex  2005   429.000000
..             ...   ...          ...
839    Vandoeuvres  2024   692.792665
859        Vernier  2024  4926.037184
879        Versoix  2024  1326.452899
899        Veyrier  2024  1858.764645
919            NaN  2024  1933.518815

[920 rows x 3 columns]

# Database logement subventionné

In [ ]:
annees = [str(annee) for annee in range(2009, 2025)]

Data_logement= []
for annee in annees:
    data_l = pd.read_excel(
        "Logement subventionnée.xls",
        sheet_name=annee,        
        skiprows=1,              
        usecols="A:B",          
        header=None,             
        names=["Commune", "Nombre_de_logements"]
    )
    data_l["Année"] = int(annee)     
    Data_logement.append(data_l) 

Data_logement_final = pd.concat(Data_logement, ignore_index=True)

Data_logement_final = Data_logement_final [["Commune", "Année", "Nombre_de_logements"]]



Data_logement_final = Data_logement_final.sort_values(by=["Commune", "Année"])


Data_logement_final = Data_logement_final.reset_index(drop=True)

print(Data_logement_final)

           Commune  Année Nombre_de_logements
0    Aire-la-Ville   2009                  24
1    Aire-la-Ville   2010                  24
2    Aire-la-Ville   2011                  24
3    Aire-la-Ville   2012                  24
4    Aire-la-Ville   2013                  24
..             ...    ...                 ...
715        Veyrier   2020                  87
716        Veyrier   2021                  87
717        Veyrier   2022                  87
718        Veyrier   2023                  87
719        Veyrier   2024                  87

[720 rows x 3 columns]
<class 'pandas.core.frame.DataFrame'>

In [125]:
logement_moyennes_par_annee = Data_logement_final.groupby('Année')['Nombre_de_logements'].mean().reset_index()

# Créer le dataframe des moyennes
#logement_moyennes =logement_moyennes_par_annee.copy()

#logement_moyennes['Commune'] = 'Moyenne_' + logement_moyennes['Année'].astype(str)

#Data_logement_final = pd.concat([Data_logement_final, logement_moyennes], ignore_index=True)
#Data_densite_final = Data_densite_final.sort_values(['Année', 'Commune'])
#print(Data_logement_final)
#Data_logement_final.to_csv("donnée_logement_subventionnée.csv")

TypeError: agg function failed [how->mean,dtype->object]

# Database population

In [ ]:
Data_pop = pd.read_excel("Population.xls")

Data_pop_reviewed = Data_pop.melt(id_vars=[Data_densite.columns[0]],var_name="Année", value_name="Population_nombre-hbt")
Data_pop_reviewed.rename(columns={Data_pop.columns[0]: "Commune"}, inplace=True)
Data_pop_reviewed = Data_pop_reviewed.sort_values(by=["Commune", "Année"])
Data_pop_reviewed = Data_pop_reviewed .reset_index(drop=True)
Data_pop_reviewed
Data_pop_reviewed.to_csv("donnée_population.csv")
Data_pop_reviewed

            Commune       Année  Population_nombre-hbt
0     Aire-la-Ville        2000                  711.0
1     Aire-la-Ville        2001                  713.0
2     Aire-la-Ville        2002                  710.0
3     Aire-la-Ville        2003                  736.0
4     Aire-la-Ville        2004                  727.0
...             ...         ...                    ...
1165        Veyrier        2021                11842.0
1166        Veyrier        2022                11936.0
1167        Veyrier        2023                11924.0
1168        Veyrier        2024                12076.0
1169        Veyrier  Unnamed: 1                    NaN

[1170 rows x 3 columns]

# Prix m2

In [ ]:
annees = [str(annee) for annee in range(2011, 2024)]

Data_prix= []
for annee in annees:
    data_p = pd.read_excel(
        "prix_m2_mediane.xls",
        sheet_name=annee,        
        skiprows=1,              
        usecols="A:B",          
        header=None,             
        names=["Commune", "prix_m2_marché_libre_Médiane"]
    )
    data_p["Année"] = int(annee)     
    Data_prix.append(data_p) 

Data_prix_final = pd.concat(Data_prix, ignore_index=True)

Data_prix_final = Data_prix_final [["Commune", "Année", "prix_m2_marché_libre_Médiane"]]



Data_prix_final = Data_prix_final.sort_values(by=["Commune", "Année"])


Data_prix_final = Data_prix_final.reset_index(drop=True)

print(Data_prix_final)
Data_prix_final.to_csv("donnée_prix_m2_mediane.csv")

                                Commune  Année prix_m2_marché_libre_Médiane
0    Autres communes de l'Est du canton   2011                         7791
1    Autres communes de l'Est du canton   2012                         9830
2    Autres communes de l'Est du canton   2013                         7257
3    Autres communes de l'Est du canton   2014                         6941
4    Autres communes de l'Est du canton   2015                         6604
..                                  ...    ...                          ...
229                             Veyrier   2019                         9390
230                             Veyrier   2020                         8807
231                             Veyrier   2021                        10658
232                             Veyrier   2022                        10153
233                             Veyrier   2023                        10690

[234 rows x 3 columns]

# Revenu brute

In [ ]:
annees = [str(annee) for annee in range(2010, 2019)]

Data_revenu= []
for annee in annees:
    data_r = pd.read_excel(
        "revenu_brut_annuel.xls",
        sheet_name=annee,        
        skiprows=1,              
        usecols="A:C",          
        header=None,             
        names=["Commune", "Médiane_couples_mariés", "Médiane_celibataire"]
    )
    data_r["Année"] = int(annee)     
    Data_revenu.append(data_r) 

Data_revenu_final = pd.concat(Data_revenu, ignore_index=True)

Data_revenu_final = Data_revenu_final [["Commune", "Année", "Médiane_couples_mariés", "Médiane_celibataire"]]



Data_revenu_final = Data_revenu_final.sort_values(by=["Commune", "Année"])


Data_revenu_final = Data_revenu_final.reset_index(drop=True)

print(Data_revenu_final)
Data_revenu_final.to_csv("donnée_revenu_brut_annuel.csv")

           Commune  Année  Médiane_couples_mariés  Médiane_celibataire
0    Aire-la-Ville   2010                  182788                56393
1    Aire-la-Ville   2011                  185509                61451
2    Aire-la-Ville   2012                  188721                58982
3    Aire-la-Ville   2013                  183835                60822
4    Aire-la-Ville   2014                  188643                62734
..             ...    ...                     ...                  ...
400        Veyrier   2014                  210336                51213
401        Veyrier   2015                  211323                52431
402        Veyrier   2016                  213176                53111
403        Veyrier   2017                  212835                52600
404        Veyrier   2018                  213093                52645

[405 rows x 4 columns]

# Superficie communes

In [ ]:
Data_superficie = pd.read_excel("superficie_par_communes.xls", names= ["Communes", "Superficie"])
Data_superficie.to_csv("donnée_superficie.csv")

# Données environnementales

In [ ]:
Data_env =pd.read_csv("energyreporter_municipality_historized.csv")
Data_env_GE = Data_env.loc[Data_env["canton"]=="GE"]
Data_env_GE = Data_env_GE[["municipality","energyreporter_date",
                           "electric_cars_per_charging_spot","elec_consumption_mwh_per_year_per_capita",
                           "renelec_production_mwh_per_year_per_capita"]]
Data_env_GE

,municipality,energyreporter_date,electric_cars_per_charging_spot,elec_consumption_mwh_per_year_per_capita,renelec_production_mwh_per_year_per_capita
100264,Aire-la-Ville,2021-03-31,NaN,NaN,NaN
100265,Aire-la-Ville,2021-04-30,NaN,NaN,NaN
100266,Aire-la-Ville,2021-05-31,NaN,NaN,NaN
100267,Aire-la-Ville,2021-06-30,NaN,NaN,NaN
100268,Aire-la-Ville,2021-07-31,NaN,NaN,NaN
...,...,...,...,...,...
102464,Veyrier,2024-11-30,36.0,2.5447,0.5953
102465,Veyrier,2024-12-31,36.6,2.5535,0.5982
102466,Veyrier,2025-01-31,48.8,2.6138,0.5973
102467,Veyrier,2025-02-28,43.6,2.3159,0.6008
102468,Veyrier,2025-03-31,38.4,2.3037,0.5918

In [ ]:
Data_env_clean= Data_env_GE.dropna()
Data_env_clean = Data_env_clean.rename(columns={'municipality': 'Commune'})
Data_env_clean = Data_env_clean.rename(columns={'energyreporter_date': 'Année'})
Data_env_clean.sort_values(by=["Commune", "Année"])
print(Data_env_clean.head(20))
Data_env_clean.to_csv("donnée_environement.csv")

              Commune       Année  electric_cars_per_charging_spot  \
100296  Aire-la-Ville  2023-11-30                              8.5
100297  Aire-la-Ville  2023-12-31                             18.5
100298  Aire-la-Ville  2024-01-31                             20.0
100299  Aire-la-Ville  2024-02-29                             20.0
100300  Aire-la-Ville  2024-03-31                              6.8
100301  Aire-la-Ville  2024-04-30                             10.8
100302  Aire-la-Ville  2024-05-31                             21.0
100303  Aire-la-Ville  2024-06-30                             20.5
100304  Aire-la-Ville  2024-07-31                             21.5
100305  Aire-la-Ville  2024-08-31                             21.5
100307  Aire-la-Ville  2024-10-31                             21.5
100308  Aire-la-Ville  2024-11-30                             21.5
100309  Aire-la-Ville  2024-12-31                             21.5
100310  Aire-la-Ville  2025-01-31                             21.5
100311  Aire-la-Ville  2025-02-28                             23.5
100312  Aire-la-Ville  2025-03-31                             24.0
100345        Anières  2023-11-30                             29.5
100346        Anières  2023-12-31                             30.0
100347        Anières  2024-01-31                             29.0
100348        Anières  2024-02-29                             28.0

        elec_consumption_mwh_per_year_per_capita  \
100296                                    3.4474
100297                                    3.4965
100298                                    3.5456
100299                                    3.6118
100300                                    3.6118
100301                                    3.5827
100302                                    3.5632
100303                                    3.5534
100304                                    3.5534
100305                                    3.3384
100307                                    3.6627
100308                                    3.6698
100309                                    3.6280
100310                                    3.5703
100311                                    3.1669
100312                                    3.1553
100345                                    3.5403
100346                                    3.5374
100347                                    3.5465
100348                                    3.5699

        renelec_production_mwh_per_year_per_capita
100296                                     34.5596
100297                                     34.5444
100298                                     34.6373
100299                                     34.5283
100300                                     34.5596
100301                                     34.3824
100302                                     31.7834
100303                                     31.7834
100304                                     31.7834
100305                                     31.0361
100307                                     31.3906
100308                                     31.4670
100309                                     31.4102
100310                                     31.0121
100311                                     30.7180
100312                                     30.6006
100345                                      0.2223
100346                                      0.2240
100347                                      0.2268
100348                                      0.2285